---
# Volumes descriptin
# example of using this temporary disk with the RAM-backed option
apiVersion: v1
kind: Pod
metadata:
  name: memory-pd
  labels:
    example: "1"
spec:
  containers:
  - name: memory-pd
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /memory-pd
        name: memory-volume
  volumes:
  - name: memory-volume
    emptyDir:
      medium: Memory
---
#
# example of using Pesrsistent Discs on GCE (GCE has to be configured)
apiVersion: v1
kind: Pod
metadata:
  name: test-gce
  labels:
    example: "2"
spec:
  containers:
  - image: nginx:latest
    ports:
    - containerPort: 80
    name: test-gce
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: gce-pd
  volumes:
  - name: gce-pd
    gcePersistentDisk:
      pdName: mysite-volume-1
      fsType: ext4