apiVersion: v1
kind: Pod
metadata:
  name: mysql-server
  labels:
    role: server
spec:
  containers:
    - name: mysql-server
      image: mysql/mysql-server:latest
      env:
      - name: PASSWORD
        value: ###
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    role: client
spec:
  containers:
    - name: mysql-client
      image: mysql/mysql-server:latest
      env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-user-pass
            key: password
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
     # lifecycle:
     #   postStart:
     #     exec: ###
---
apiVersion: v1
data:
   password: cXdlcnR5
   username: cm9vdA==
kind: Secret
metadata:
  name: db-user-pass  
type: Opaque
