---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD
      application: www
  template:
    metadata:
      labels:
        application: www
=======
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
>>>>>>> 10e3b8c205860211d5a5fa4406d8981a3919006c
    spec:
      containers:
      - name: nginx
        image: butuzov/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
<<<<<<< HEAD
          - name: www-vol
            mountPath: /usr/share/nginx/html
      volumes:
        - name: www-vol
          persistentVolumeClaim:
            claimName: myclaim
      initContainers:
      - name: init-curl
        image: uzyexe/curl
        volumeMounts:
        - name: www-vol
          mountPath: "/usr/share/nginx/html"
        command: ['sh', '-c', 'curl http://www.linux.org.ru > /usr/share/nginx/html/index.html']
=======
          - name: www
            mountPath: /usr/share/nginx/html
>>>>>>> 10e3b8c205860211d5a5fa4406d8981a3919006c
---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
<<<<<<< HEAD
    application: www
=======
    app: nginx
>>>>>>> 10e3b8c205860211d5a5fa4406d8981a3919006c
  ports:
  - port: 80
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
<<<<<<< HEAD
    requests:
      storage: 100Mi
  
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv01
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 512Mi
=======
    storage: 512Mb
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Mb
>>>>>>> 10e3b8c205860211d5a5fa4406d8981a3919006c
