---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      application: www
  template:
    metadata:
      labels:
        application: www
    spec:
      containers:
      - name: nginx
        image: butuzov/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: www-vol
            mountPath: /usr/share/nginx/html
      volumes:
        - name: www-vol
          persistentVolumeClaim:
            claimName: myclaim
      initContainers:
      - name: init-curl
        image: uzyexe/curl
        volumeMounts:
        - name: www-vol
          mountPath: "/usr/share/nginx/html"
        command: ['sh', '-c', 'curl http://www.linux.org.ru > /usr/share/nginx/html/index.html']
---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    application: www
  ports:
  - port: 80
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv01
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 512Mi
