apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: web-1
spec:
  containers:
    - name: nginx
      image: butuzov/nginx:latest
      ports:
        - containerPort: 8081
      volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx/conf.d/
  volumes:
    - name: config-volume
      configMap:
        name: nginx-1-conf
        items:
        - key: nginx-1.conf
          path: default.conf
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: web-2
spec:
  containers:
    - name: nginx
      image: butuzov/nginx:latest
      ports:
        - containerPort: 8082
      volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx/conf.d/
  volumes:
    - name: config-volume
      configMap:
        name: nginx-2-conf
        items:
        - key: nginx-2.conf
          path: default.conf
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-web
spec:
  selector: 
    run: web-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2-web
spec:
  selector: 
    run: web-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-1-conf
data:
  nginx-1.conf: "server {\n    listen       8081;\n    server_name  localhost;\n\n
      \   location / {\n        root   /usr/share/nginx/html;\n        index  index.html
      index.htm;\n    }\n    error_page   500 502 503 504  /50x.html;\n    location
      = /50x.html {\n        root   /usr/share/nginx/html;\n    }\n}\n"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-2-conf
data:
  nginx-2.conf: "server {\n    listen       8082;\n    server_name  localhost;\n\n
      \   location / {\n        root   /usr/share/nginx/html;\n        index  index.html
      index.htm;\n    }\n    error_page   500 502 503 504  /50x.html;\n    location
      = /50x.html {\n        root   /usr/share/nginx/html;\n    }\n}\n"