apiVersion: v1
kind: Pod
metadata:
  name: mysql-server
  labels:
    role: server
spec:
  containers:
    - name: mysql-server
      image: mysql/mysql-server:latest
      env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-password
            key: password
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    role: client
spec:
  containers:
    - name: mysql-client
      image: mysql/mysql-server:latest
      env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-password
            key: password
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "yum update; yum -y install git"]
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    role: server
  ports:
  - port: 3306
---
apiVersion: v1
data:
   password: cXdlcnR5
   username: cm9vdA==
kind: Secret
metadata:
  name: mysql-password  
type: Opaque
